docs: Specify service_type for Gateway endpoint
This commit adds `service_type` to example code at README since
current sample code causes the following error:

> Error: no matching EC2 VPC Endpoint Service found